name: Data CD

on:
  push:
    branches:
      - main

jobs:

  deploy-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Deploy to TEST
        run: |
          echo "Deploying Data pipeline to TEST..."
          sleep 3
          echo "TEST deployment successful"


  deploy-prod:
    needs: deploy-test
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to PROD
        run: |
          echo "Deploying Data pipeline to PROD..."
          sleep 3
          echo "PROD deployment successful"